version: '3.7'

services:
 db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    labels:
      - webNotes-db
    environment:
      SA_PASSWORD: TheStr0ngestP@ssw0rdEver
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/lib/sqlserver/data

volumes:
  sqlserverdata: